import Foundation

// A Theme is a set of synthesis parameters. Clonk ships zero audio files —
// every click is generated by DSP from these numbers (see Synth.swift).
//
// The model: a short noise burst (the switch impact) excites two bandpass
// resonators (the keycap/plate/case body), summed with a bright high-passed
// transient (the contact "click"). Resonated noise reads as a real "thock",
// not a musical tone.
struct Theme: Identifiable, Equatable {
    let id: String
    let name: String

    var exciteDecay: Double     // s — length of the noise burst exciting the body

    var res1Freq: Double        // Hz — low body resonance
    var res1Q: Double
    var res1Gain: Double
    var res2Freq: Double        // Hz — upper body resonance
    var res2Q: Double
    var res2Gain: Double

    var clickGain: Double       // 0…1 — bright contact transient level
    var clickDecay: Double      // s
    var clickHighpass: Double   // Hz — transient brightness

    var totalDecay: Double      // s — master amplitude decay; keeps clicks crisp

    var releaseGain: Double     // 0…1 relative to press, 0 disables release sound
    var releaseBright: Double   // >1 makes the release lighter/thinner than the press

    var gain: Double            // overall output trim
    var pitchJitter: Double     // 0…1 random per-press detune for realism
}

extension Theme {
    // Five distinct voices, each modelled on a real switch archetype.
    static let builtIns: [Theme] = [
        // Clicky (Cherry MX Blue style) — sharp, bright, audible click jacket.
        Theme(id: "clicky", name: "Clicky Blue",
              exciteDecay: 0.004,
              res1Freq: 210, res1Q: 3.0, res1Gain: 0.50,
              res2Freq: 2600, res2Q: 6.0, res2Gain: 0.70,
              clickGain: 1.0, clickDecay: 0.006, clickHighpass: 3500,
              totalDecay: 0.055, releaseGain: 0.5, releaseBright: 1.4,
              gain: 0.85, pitchJitter: 0.08),

        // Tactile (Cherry MX Brown style) — balanced bump, the all-rounder.
        Theme(id: "tactile", name: "Tactile Brown",
              exciteDecay: 0.006,
              res1Freq: 170, res1Q: 2.5, res1Gain: 0.60,
              res2Freq: 1100, res2Q: 4.0, res2Gain: 0.45,
              clickGain: 0.5, clickDecay: 0.007, clickHighpass: 2200,
              totalDecay: 0.07, releaseGain: 0.45, releaseBright: 1.3,
              gain: 0.9, pitchJitter: 0.07),

        // Linear (Cherry MX Red style) — smooth, no click, deeper and softer.
        Theme(id: "linear", name: "Linear Red",
              exciteDecay: 0.009,
              res1Freq: 120, res1Q: 2.0, res1Gain: 0.80,
              res2Freq: 700, res2Q: 3.0, res2Gain: 0.30,
              clickGain: 0.18, clickDecay: 0.008, clickHighpass: 1500,
              totalDecay: 0.08, releaseGain: 0.35, releaseBright: 1.25,
              gain: 0.85, pitchJitter: 0.06),

        // Deep, rounded "thock" — premium gasket-mounted board feel.
        Theme(id: "thock", name: "Deep Thock",
              exciteDecay: 0.012,
              res1Freq: 85, res1Q: 2.2, res1Gain: 1.0,
              res2Freq: 420, res2Q: 3.0, res2Gain: 0.40,
              clickGain: 0.22, clickDecay: 0.009, clickHighpass: 1100,
              totalDecay: 0.105, releaseGain: 0.4, releaseBright: 1.2,
              gain: 0.9, pitchJitter: 0.05),

        // Vintage typewriter / buckling spring — loud, metallic high ping.
        Theme(id: "typewriter", name: "Vintage Typewriter",
              exciteDecay: 0.005,
              res1Freq: 240, res1Q: 3.0, res1Gain: 0.50,
              res2Freq: 3200, res2Q: 14.0, res2Gain: 0.55,
              clickGain: 0.95, clickDecay: 0.010, clickHighpass: 3000,
              totalDecay: 0.12, releaseGain: 0.55, releaseBright: 1.5,
              gain: 0.95, pitchJitter: 0.10),
    ]

    static let defaultID = "tactile"

    static func builtIn(id: String) -> Theme {
        builtIns.first { $0.id == id } ?? builtIns[0]
    }

    // Voices available for the mouse — the dedicated click plus every keyboard
    // voice, so the mouse can be configured independently.
    static var mouseVoices: [Theme] { [mouseClick] + builtIns }

    static func mouseVoice(id: String) -> Theme {
        mouseVoices.first { $0.id == id } ?? mouseClick
    }

    // Scroll-wheel detent ticks — short dry clicks, one per notch of scroll.
    static let scrollVoices: [Theme] = [
        Theme(id: "notched", name: "Notched Wheel",
              exciteDecay: 0.002,
              res1Freq: 320, res1Q: 3.0, res1Gain: 0.30,
              res2Freq: 2400, res2Q: 5.0, res2Gain: 0.35,
              clickGain: 0.80, clickDecay: 0.004, clickHighpass: 3000,
              totalDecay: 0.030, releaseGain: 0, releaseBright: 1.0,
              gain: 0.70, pitchJitter: 0.12),
        Theme(id: "soft-wheel", name: "Soft Wheel",
              exciteDecay: 0.004,
              res1Freq: 260, res1Q: 2.0, res1Gain: 0.40,
              res2Freq: 1400, res2Q: 3.0, res2Gain: 0.25,
              clickGain: 0.35, clickDecay: 0.005, clickHighpass: 1800,
              totalDecay: 0.040, releaseGain: 0, releaseBright: 1.0,
              gain: 0.62, pitchJitter: 0.10),
        Theme(id: "ratchet", name: "Ratchet",
              exciteDecay: 0.0015,
              res1Freq: 400, res1Q: 3.0, res1Gain: 0.25,
              res2Freq: 3400, res2Q: 9.0, res2Gain: 0.40,
              clickGain: 1.0, clickDecay: 0.0035, clickHighpass: 4000,
              totalDecay: 0.028, releaseGain: 0, releaseBright: 1.0,
              gain: 0.72, pitchJitter: 0.14),
    ]

    static let scrollDefaultID = "notched"

    static func scrollVoice(id: String) -> Theme {
        scrollVoices.first { $0.id == id } ?? scrollVoices[0]
    }

    // Find any theme by id across every voice family — used for Advanced
    // overrides which can pick from the entire palette.
    static func any(id: String) -> Theme? {
        if let t = builtIns.first(where: { $0.id == id }) { return t }
        if mouseClick.id == id { return mouseClick }
        return scrollVoices.first { $0.id == id }
    }

    // Dedicated voice for mouse clicks — dry and crisp, with a lighter
    // release "clack" for the old-fashioned full mouse-button sound.
    static let mouseClick = Theme(
        id: "_mouse", name: "Mouse",
        exciteDecay: 0.003,
        res1Freq: 300, res1Q: 2.0, res1Gain: 0.30,
        res2Freq: 1800, res2Q: 3.0, res2Gain: 0.30,
        clickGain: 0.85, clickDecay: 0.006, clickHighpass: 2800,
        totalDecay: 0.06, releaseGain: 0.92, releaseBright: 1.12,
        gain: 0.8, pitchJitter: 0.07)
}
